// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRtWmK0wNdv9wcAYUU7EILURkfNFjRxog',
    appId: '1:774249484665:web:5c6c0e2e2f36edbde39fa8',
    messagingSenderId: '774249484665',
    projectId: 'flash-chat-af1c0',
    authDomain: 'flash-chat-af1c0.firebaseapp.com',
    storageBucket: 'flash-chat-af1c0.firebasestorage.app',
    measurementId: 'G-72ZTN5246R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6rza1uxRP0ibDcBRUE71NUsIRQkb-JoU',
    appId: '1:774249484665:android:33dba105dbadb8dfe39fa8',
    messagingSenderId: '774249484665',
    projectId: 'flash-chat-af1c0',
    storageBucket: 'flash-chat-af1c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpv9d-P_8gTu9CwY1jB-AylFdsOL3LFyo',
    appId: '1:774249484665:ios:20b893c10c60e5b6e39fa8',
    messagingSenderId: '774249484665',
    projectId: 'flash-chat-af1c0',
    storageBucket: 'flash-chat-af1c0.firebasestorage.app',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpv9d-P_8gTu9CwY1jB-AylFdsOL3LFyo',
    appId: '1:774249484665:ios:20b893c10c60e5b6e39fa8',
    messagingSenderId: '774249484665',
    projectId: 'flash-chat-af1c0',
    storageBucket: 'flash-chat-af1c0.firebasestorage.app',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRtWmK0wNdv9wcAYUU7EILURkfNFjRxog',
    appId: '1:774249484665:web:e249681e3dee72c6e39fa8',
    messagingSenderId: '774249484665',
    projectId: 'flash-chat-af1c0',
    authDomain: 'flash-chat-af1c0.firebaseapp.com',
    storageBucket: 'flash-chat-af1c0.firebasestorage.app',
    measurementId: 'G-NYQ4S0CCHL',
  );
}
